// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC52zCfb9n74Y5IPdlQVqmqB_GufTlPeTg',
    appId: '1:341580860242:web:c011935a25b5008f7fc88b',
    messagingSenderId: '341580860242',
    projectId: 'johoclone',
    authDomain: 'johoclone.firebaseapp.com',
    storageBucket: 'johoclone.appspot.com',
    measurementId: 'G-0Z1F32TB0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8BqNH1Tx0J33FE9cbkPlZ2vv-xrcHRoM',
    appId: '1:341580860242:android:7ffb1723d0af06867fc88b',
    messagingSenderId: '341580860242',
    projectId: 'johoclone',
    storageBucket: 'johoclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6G1-zNQ_sfR2W5pszsAJLtc3WKYBoD7E',
    appId: '1:341580860242:ios:264ccd3962b2b8ee7fc88b',
    messagingSenderId: '341580860242',
    projectId: 'johoclone',
    storageBucket: 'johoclone.appspot.com',
    iosBundleId: 'com.example.cloneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6G1-zNQ_sfR2W5pszsAJLtc3WKYBoD7E',
    appId: '1:341580860242:ios:264ccd3962b2b8ee7fc88b',
    messagingSenderId: '341580860242',
    projectId: 'johoclone',
    storageBucket: 'johoclone.appspot.com',
    iosBundleId: 'com.example.cloneapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC52zCfb9n74Y5IPdlQVqmqB_GufTlPeTg',
    appId: '1:341580860242:web:76388eed181e15957fc88b',
    messagingSenderId: '341580860242',
    projectId: 'johoclone',
    authDomain: 'johoclone.firebaseapp.com',
    storageBucket: 'johoclone.appspot.com',
    measurementId: 'G-BGQJBQ2VDQ',
  );
}
